version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    parallelism: 3 # run three instances of this job in parallel
    docker: # run the steps with Docker
      - image: circleci/ruby:2.6.0-node-browsers-legacy # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          PGHOST: 127.0.0.1
          PGUSER: circleci-poke-tracker_test
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine # database image
        environment: # environment variables for database
          POSTGRES_USER: circleci-poke-tracker_test
          POSTGRES_DB: poke-tracker_test
          POSTGRES_PASSWORD: ""
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - ruby-dependencies-v1-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-v1-

      - run: # Install Ruby dependencies
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: ruby-dependencies-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - webpacker-dependencies-v1-{{ checksum "yarn.lock" }}
            - webpacker-dependencies-v1-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m


      # Store yarn / webpacker cache
      - save_cache:
          key: webpacker-dependencies-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec massa -V

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      # Save the tests split for replication of failures with the same seed
      - store_artifacts:
          path: test_results
          destination: test_results